config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root 'tasks#index', as: :authenticated_root
  end

  root 'pages#home'

  get 'about' => 'pages#about'

  resources :tasks do
    member do
      put :mark_as_todo
      put :mark_as_doing
      put :mark_as_done
    end
  end

  devise_for :users

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :content, presence: true
  validates :content, uniqueness: {scope: [:content, :user]}

  belongs_to :user

  enum status: [ :todo, :doing, :done ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy,
    :mark_as_todo, :mark_as_doing, :mark_as_done]

  before_action :authorized_user!, except: [:index, :new, :create]
  before_action :authenticate_user!

  def index
    @todo_tasks = current_user.tasks.todo
    @doing_tasks = current_user.tasks.doing
    @done_tasks = current_user.tasks.done
  end

  def new
    @task = current_user.tasks.build
  end

  def edit
  end

  def create
    @task = current_user.tasks.new task_params

    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  def mark_as_todo
    @task.todo!
    redirect_to tasks_path
  end

  def mark_as_doing
    @task.doing!
    redirect_to tasks_path
  end

  def mark_as_done
    @task.done!
    redirect_to tasks_path
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:content)
    end

    def authorized_user!
      @task = current_user.tasks.find_by(id: params[:id])
      redirect_to tasks_path, notice: "Not authorized to edit this task" if @task.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<i class="fa fa-circle-o-notch"></i> TODO Box'.html_safe, root_path, class: 'title-font navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <div class="navbar-form navbar-left">
              <%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
            </div>
          </li>
          <li> <%= link_to 'Tasks', tasks_path %> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Profile
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'Edit', edit_user_registration_path %></li>
              <li><a href="#">Another action</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Configurations</a></li>
              <li role="separator" class="divider"></li>
              <li> <%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to 'Login', new_user_session_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1> <i class="fa fa-circle-o-notch"></i> TODO Flow</h1>
  <p>
    This is my smart TODO list!
  </p>

  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary' %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, html: {class: 'form-signin'}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :content, label: false, required: true, placeholder: 'Content' %>
  <%= f.button :submit, class: 'btn btn-primary btn-block' %>
  <%= link_to 'Back', tasks_path, class: 'btn btn-default btn-block' %>
<% end %>

app/views/tasks/_status_links.html.erb
<% if task.doing? %>
  <%= link_to '<i class="fa fa-arrow-left"></i>'.html_safe, mark_as_todo_task_path(task), method: :put, class: 'btn btn-info' %>
  <%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, mark_as_done_task_path(task), method: :put, class: 'btn btn-info' %>
<% elsif task.todo? %>
  <%= link_to '<i class="fa fa-arrow-right"></i>'.html_safe, mark_as_doing_task_path(task), method: :put, class: 'btn btn-info' %>
<% else %>
  <%= link_to '<i class="fa fa-arrow-left"></i>'.html_safe, mark_as_doing_task_path(task), method: :put, class: 'btn btn-info' %>
<% end %>

app/views/tasks/_task.html.erb
<div class="panel panel-info">
  <div class="panel-heading">
    Created <%= time_ago_in_words task.created_at %> ago
    <div class="row pull-right">
      <div class="col-md-6">
        <%= link_to fa_icon('pencil') , edit_task_path(task) %>
      </div>
      <div class="col-md-6">
        <%= link_to fa_icon('trash'), task, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    </div>
  <div class="panel-body">
    <%= simple_format auto_link task.content, html: { target: '_blank' } %>
  </div>
  <div class="panel-footer text-center btn-group btn-group-justified">
    <%= render 'status_links', task: task %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1 class="text-center">Editing Task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <h2 class="text-center">To Do</h2>
    <%= render @todo_tasks %>
  </div>
  <div class="col-md-4">
    <h2 class="text-center">Doing</h2>
    <%= render @doing_tasks %>
  </div>
  <div class="col-md-4">
    <h2 class="text-center">Done</h2>
    <%= render @done_tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1 class="text-center">New Task</h1>
<%= render 'form' %>